/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_pax_genpwd_jni_Sha1Utils */

#ifndef _Included_com_pax_genpwd_jni_Sha1Utils
#define _Included_com_pax_genpwd_jni_Sha1Utils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_pax_genpwd_jni_Sha1Utils
 * Method:    calcSha1
 * Signature: (Ljava/lang/String;ILjava/lang/String;I)[I
 */
JNIEXPORT jbyteArray JNICALL Java_com_pax_genpwd_jni_Sha1Utils_calcSha1
        (JNIEnv *, jobject, jstring, jint, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
